### ISSUE TITLE
[bug] missingPlugin 'objectRestSpread'

### ISSUE THREAD

**Issue by gullitmiranda** [jean343/styless#34]
after upgrading to v1.4.14 babel started to report the error:
```
Error converting the less syntax for the file: /app/src/jarvis/src/button/Button.js styled(({ fluid, ...rest }) => <AntButton {...rest} />)`
  && {
    width: if(@fluid, 100%, auto);
  }
` { SyntaxError: This experimental syntax requires enabling the parser plugin: 'objectRestSpread' (1:18) - make sure this is an expression.
> 1 | (styled(({ fluid, ...rest }) => <AntButton {...rest} />)`&& {
    |                   ^
  2 |   width: ${props => (!![props["fluid"],(props.theme || {})["fluid"]].filter(v => v !== void 0)[0]) ? `100%` : `auto`};
  3 | }`)
    at Parser.raise (/app/node_modules/@babel/parser/lib/index.js:3939:15)
    at Parser.expectPlugin (/app/node_modules/@babel/parser/lib/index.js:5253:18)
    at Parser.parseObj (/app/node_modules/@babel/parser/lib/index.js:6670:14)
    at Parser.parseExprAtom (/app/node_modules/@babel/parser/lib/index.js:6294:21)
    at Parser.parseExprSubscripts (/app/node_modules/@babel/parser/lib/index.js:5924:21)
    at Parser.parseMaybeUnary (/app/node_modules/@babel/parser/lib/index.js:5903:21)
    at Parser.parseExprOps (/app/node_modules/@babel/parser/lib/index.js:5812:21)
    at Parser.parseMaybeConditional (/app/node_modules/@babel/parser/lib/index.js:5784:21)
    at Parser.parseMaybeAssign (/app/node_modules/@babel/parser/lib/index.js:5731:21)
    at Parser.parseParenAndDistinguishExpression (/app/node_modules/@babel/parser/lib/index.js:6482:28)
  pos: 18,
  loc: Position { line: 1, column: 18 },
  missingPlugin: [ 'objectRestSpread' ],
  code: 'BABEL_REPLACE_SOURCE_ERROR' }
```

**Comment by gullitmiranda** [comment]
and with external variable:

```js
const antBtnClassName = "ant-btn";
const size = {
  small: "1rem",
  regular: "1.2rem",
  medium: "1.4rem",
  mediumplus: "1.8rem",
  big: "2.0rem",
  large: "2.4rem",
  xlarge: "3.2rem"
}
```

```
Error converting the less syntax for the file: /app/src/modules/Process/ProcessDetailView.js styled(Link)`
  &.${antBtnClassName} {
    font-size: ${size.xlarge};
    font-weight: 700;
    width: 40px;
    text-decoration: none;
    padding: 0;

    &,
    &:hover,
    &:focus,
    &:active,
    &.active {
      background: none;
      border-color: transparent;
    }
  }
` { [Error: Unrecognised input]
  message: 'Unrecognised input',
  stack: undefined,
  type: 'Parse',
  filename: 'input',
  index: 4,
  line: 2,
  column: 3,
  callLine: NaN,
  callExtract: undefined,
  extract:
   [ '',
     '  &.${antBtnClassName} {',
     '    font-size: ${size.xlarge};' ] }
```

**Comment by jean343** [comment]
That was a really good catch, thanks!
There is a test case just for this now 👍
